server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    
    
#MyBatis
mybatis:
# mapper-locations: classpath*:/mapper/postgres/*.xml
  mapper-locations: classpath*:/com.benkyo.repository/*.xml

#プロファイル
#spring.profiles.active: develop

#ログ設定
logging: 
  config: classpath:logback-spring.xml
  level: 
    root: INFO
    org.springframework.web: DEBUG # コンソールに出力されるログのレベルを変更(Unknown Propertyって出るけど機能してる)
    appLogger: DEBUG
